name: Build and deploy JAR app to Azure Web App - SongLyricCMS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        working-directory: ./ITMD544_SongLyric
        run: mvn clean install -DskipTests

      - name: List target directory
        run: Get-ChildItem -Force ./ITMD544_SongLyric/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: './ITMD544_SongLyric/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files (debug)
        run: Get-ChildItem -Force


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4BE557F91535436C8E9F8B4B42057842 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76E091A2DD894D14A65BA387C4B4A778 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F379D1DA7C1B4340AB63D58B5B003006 }}

      - name: Set Environment Variables for Secrets
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "HIVE_API_KEY=${{ secrets.HIVE_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SongLyricCMS'
          slot-name: 'Production'
          package: 'ITMD544_SongLyric/target/*.jar'